/** Orbital nodes for the hero Transformation Universe */

export const homeUniverseNodes = [
  {
    id: 'strategy',
    label: 'Szervezetfejlesztés',
    tooltipTitle: 'Szervezetfejlesztés',
    tooltipText: 'Megvalósítható stratégia kialakítása a cselekvésig.',
    link: '/tanacsadas',
    angle: -88,
    radius: 178,
    orbitDuration: 95,
    scale: 1.06,
    opacity: 1,
    doubleRing: true,
    bend: 0.14,
  },
  {
    id: 'leadership',
    label: 'Vezetőfejlesztés',
    tooltipTitle: 'Vezetőfejlesztés',
    tooltipText: 'Egyéni megközelítés a vezetői döntések támogatásához.',
    link: '/tanacsadas',
    angle: -38,
    radius: 192,
    orbitDuration: 110,
    scale: 0.94,
    opacity: 0.92,
    doubleRing: false,
    bend: 0.1,
  },
  {
    id: 'hr',
    label: 'HR tanácsadás',
    tooltipTitle: 'HR tanácsadás',
    tooltipText: 'Emberek fejlesztése és szervezeti támogatás.',
    link: '/tanacsadas',
    angle: 18,
    radius: 185,
    orbitDuration: 88,
    scale: 1.08,
    opacity: 1,
    doubleRing: true,
    bend: 0.16,
  },
  {
    id: 'training',
    label: 'Képzések',
    tooltipTitle: 'Felnőttképzés',
    tooltipText: 'Minőségi képzések a XXI. század kulcskompetenciáihoz.',
    link: '/felnottkepzes',
    angle: 72,
    radius: 198,
    orbitDuration: 102,
    scale: 0.9,
    opacity: 0.88,
    doubleRing: false,
    bend: 0.11,
  },
  {
    id: 'mentally',
    label: 'Mentally',
    tooltipTitle: 'Mentally',
    tooltipText: 'Digitális támogatás a mentális egészségért.',
    link: '/mentally',
    angle: 128,
    radius: 182,
    orbitDuration: 92,
    scale: 1.02,
    opacity: 0.95,
    doubleRing: true,
    bend: 0.13,
  },
  {
    id: 'grants',
    label: 'Pályázatok',
    tooltipTitle: 'Pályázatok',
    tooltipText: 'EU-forrásból megvalósuló fejlesztési projektek támogatása.',
    link: '/palyazatok',
    angle: 168,
    radius: 190,
    orbitDuration: 105,
    scale: 0.96,
    opacity: 0.9,
    doubleRing: false,
    bend: 0.15,
  },
  {
    id: 'results',
    label: 'Referenciák',
    tooltipTitle: 'Referenciák',
    tooltipText: 'Mérhető fejlesztés, tartós szervezeti változás.',
    link: '/referenciak',
    angle: 208,
    radius: 186,
    orbitDuration: 98,
    scale: 1.04,
    opacity: 1,
    doubleRing: true,
    bend: 0.12,
  },
  {
    id: 'contact',
    label: 'Kapcsolat',
    tooltipTitle: 'Kapcsolat',
    tooltipText: 'Keressen minket bizalommal — személyes konzultáció.',
    link: '/kapcsolat',
    angle: 248,
    radius: 194,
    orbitDuration: 108,
    scale: 0.92,
    opacity: 0.86,
    doubleRing: false,
    bend: 0.17,
  },
] as const;

export const homeUniverseCenter = {
  title: 'RÁVEZETŐ',
} as const;

/** Decorative micro-nodes — ambient depth, not interactive */
export const homeUniverseSecondaryNodes = [
  { angle: -62, radius: 158, size: 3 },
  { angle: -12, radius: 172, size: 2 },
  { angle: 42, radius: 168, size: 3 },
  { angle: 98, radius: 176, size: 2 },
  { angle: 148, radius: 164, size: 3 },
  { angle: 188, radius: 178, size: 2 },
  { angle: 228, radius: 170, size: 3 },
  { angle: 268, radius: 162, size: 2 },
  { angle: 308, radius: 174, size: 3 },
  { angle: 338, radius: 166, size: 2 },
] as const;
